// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agreements" | "/forgot-password" | "/home" | "/landowner/requests/[id]" | "/listings" | "/listings/[id]" | "/listings/[id]/edit" | "/listings/mine" | "/listings/new" | "/map" | "/matches" | "/messages" | "/onboarding" | "/payments/transport/cancel" | "/payments/transport/sandbox" | "/payments/transport/success" | "/profile" | "/properties/[slug]" | "/register" | "/request/new" | "/requests" | "/requests/matches" | "/requests/new" | "/requests/new/requirements" | "/requests/sent" | "/sign-in" | "/sign-up" | "/transport" | "/transport/[id]" | "/transport/available" | "/transport/calendar" | "/transport/earnings" | "/transport/jobs" | "/transport/quotes/[id]" | "/update-password" | "/workspace" | "/workspace/[id]" | "/workspaces/[id]" | "/workspaces/[id]/agreement" | "/workspaces/[id]/review"
type AppRouteHandlerRoutes = "/api/locations/geocode" | "/api/payments/agistment-settlement" | "/api/payments/transport/checkout" | "/api/webhooks/stripe" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agreements": {}
  "/api/locations/geocode": {}
  "/api/payments/agistment-settlement": {}
  "/api/payments/transport/checkout": {}
  "/api/webhooks/stripe": {}
  "/auth/callback": {}
  "/forgot-password": {}
  "/home": {}
  "/landowner/requests/[id]": { "id": string; }
  "/listings": {}
  "/listings/[id]": { "id": string; }
  "/listings/[id]/edit": { "id": string; }
  "/listings/mine": {}
  "/listings/new": {}
  "/map": {}
  "/matches": {}
  "/messages": {}
  "/onboarding": {}
  "/payments/transport/cancel": {}
  "/payments/transport/sandbox": {}
  "/payments/transport/success": {}
  "/profile": {}
  "/properties/[slug]": { "slug": string; }
  "/register": {}
  "/request/new": {}
  "/requests": {}
  "/requests/matches": {}
  "/requests/new": {}
  "/requests/new/requirements": {}
  "/requests/sent": {}
  "/sign-in": {}
  "/sign-up": {}
  "/transport": {}
  "/transport/[id]": { "id": string; }
  "/transport/available": {}
  "/transport/calendar": {}
  "/transport/earnings": {}
  "/transport/jobs": {}
  "/transport/quotes/[id]": { "id": string; }
  "/update-password": {}
  "/workspace": {}
  "/workspace/[id]": { "id": string; }
  "/workspaces/[id]": { "id": string; }
  "/workspaces/[id]/agreement": { "id": string; }
  "/workspaces/[id]/review": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
