// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/(app)/agreements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agreements">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/agreements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/listings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/listings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/listings/mine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/mine">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/listings/mine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/listings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/listings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/request/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/request/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/request/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/available/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/available">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/available/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/calendar">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/earnings">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/jobs">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/transport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/transport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/workspace/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/workspace/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(app)/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(auth)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(auth)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(auth)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(auth)/update-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/update-password">> = Specific
  const handler = {} as typeof import("../../../../src/app/(auth)/update-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/landowner/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landowner/requests/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/landowner/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/payments/transport/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/transport/cancel">> = Specific
  const handler = {} as typeof import("../../../../src/app/payments/transport/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/payments/transport/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/transport/sandbox">> = Specific
  const handler = {} as typeof import("../../../../src/app/payments/transport/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/payments/transport/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/transport/success">> = Specific
  const handler = {} as typeof import("../../../../src/app/payments/transport/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/properties/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/properties/[slug]">> = Specific
  const handler = {} as typeof import("../../../../src/app/properties/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/requests/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/matches">> = Specific
  const handler = {} as typeof import("../../../../src/app/requests/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/requests/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/requests/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/requests/new/requirements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/new/requirements">> = Specific
  const handler = {} as typeof import("../../../../src/app/requests/new/requirements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/requests/sent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/sent">> = Specific
  const handler = {} as typeof import("../../../../src/app/requests/sent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/transport/quotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/transport/quotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/workspaces/[id]/agreement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces/[id]/agreement">> = Specific
  const handler = {} as typeof import("../../../../src/app/workspaces/[id]/agreement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/workspaces/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/workspaces/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/workspaces/[id]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces/[id]/review">> = Specific
  const handler = {} as typeof import("../../../../src/app/workspaces/[id]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/locations/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/geocode">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/locations/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/payments/agistment-settlement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/agistment-settlement">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/payments/agistment-settlement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
